### ISSUE TITLE
Question about input parameter

### ISSUE THREAD

**Issue by SQFeng01** [LeszekSwirski/singleeyefitter#4]
I'm trying to run the executable file SingleEyeFitterCmd but a little bit confused about the parameters we should feed. 
`        std::cerr << "USAGE: " << argv[0] << " <folder> <filepattern> <fov> [<truthfile> [<init_num_added>]]" << std::endl;`
Could you please explain the meaning of filepattern and what is the FOV for the dataset you used? Besides, are the last two parameters optional and their use case?
Thank you very much.

**Comment by LeszekSwirski** [comment]
<filepattern> is for filtering which files in the folder to process, either specified as a regex "/like this/" or as a filename with # as a number placeholder (see https://github.com/LeszekSwirski/singleeyefitter/blob/master/cmd/SingleEyeFitterCmd.cpp#L322)

The FOV I used was, IIRC, 45 deg.

The last two parameters are indeed optional -- <truthfile> was used for comparing calculated values against a ground truth file, and <init_num_added> was for limiting how many images are used for the initial model estimate (which could then be refined by adding more images, with the 'a' key). These were useful for my research, but probably not for anyone else unless they're trying to reproduce my results.
