### ISSUE TITLE
Example input

### ISSUE THREAD

**Issue by lizha0yan** [LeszekSwirski/singleeyefitter#5]
Hi Leszek,
I'm very interested in this project. I already set up the environment for this, can you provide some sample input or explanation? I'm confused about what is expected as input here:
`std::cerr << "USAGE: " << argv[0] << " <folder> <filepattern> <fov> [<truthfile> [<init_num_added>]]" << std::endl;`

Another question, does the gaze_vector only comes from ground_truth? I saw the dataset you provide in [link](https://www.cl.cam.ac.uk/research/rainbow/projects/eyemodelfit/) only has original eye images. Then how can we still get the gaze direction estimation?

Regards,
Zhaoyan

**Comment by LeszekSwirski** [comment]
Hi, I'm afraid I haven't touched this work in a long time and don't have any sample ground truth inputs anymore. You could maybe generate new ones using https://github.com/LeszekSwirski/eyemodel. For the rest of the input parameters, see #4 .

**Comment by lizha0yan** [comment]
That's really helpful! Now I got it ran successfully. Just curious, what does the [gaze vector](https://github.com/LeszekSwirski/singleeyefitter/blob/master/lib/SingleEyeFitter.cpp#L1633) represent? Do we use the center of the image as the origin and the gaze vector represents direction?

**Comment by LeszekSwirski** [comment]
IIRC that's right, the center of the image is the origin, and the projected gaze vector is a 2D projection vector of the 3D gaze direction, in the direction of the line connecting the eye centre to the pupil centre.
